image: dkr-reg1.mipn:5000/ll_dlep_debian_stable_build

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cd build
    - mkdir release
    - cmake -DCMAKE_INSTALL_PREFIX:PATH=./release ..
    - make install
  artifacts:
    name: "${CI_PROJECT_NAME}"
    paths:
      - "build/release"

test:
  stage: test
  dependencies:
    - build
  script:
    - cd build
#    - cmake ..
#    - make
    - make test

deploy:
  stage: deploy
  dependencies:
    - build
    - test
  only:
    refs:
      - master
    variables:
      - $CI_PROJECT_NAMESPACE == "laf"
  script:
    - pwd
    - ls -al
    - curl -vfs -u ${NEXUS_USERNAME}:${NEXUS_PASSWORD} --upload-file "${CI_PROJECT_NAME}.zip" "${NEXUS_STAGING_DIR}/${CI_PROJECT_NAME}-binaries.zip"
